openapi: 3.0.0
info:
  title: Fitness & Nutrition API
  version: 1.0.0
servers:
  - url: https://damp-spire-30962-30b3ab2de5a2.herokuapp.com
paths:
  /add-grocery-item:
    get:
      summary: Add item to grocery list
      parameters:
        - name: item_name
          in: query
          required: true
          schema:
            type: string
        - name: quantity
          in: query
          schema:
            type: integer
        - name: category
          in: query
          schema:
            type: string
        - name: priority
          in: query
          schema:
            type: string
            enum: [High, Medium, Low]
      security:
        - basicAuth: []
      responses:
        '200':
          description: Item added
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  # Add other endpoints following the same pattern

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic